### ISSUE TITLE
Can it be use using Adafruit Arduino library instead of FastLED? 

### ISSUE THREAD

**Issue by Adzrael** [systembolaget/Physical-computing-tutorial-8b-Programmable-NeoPixel-RGB-LED-ring#1]
I am new to coding and try to learn using Tinkercad but it does not include FastLED Arduino library, can this be replicate by using the Adafruit Arduino library? If yes, can you help me with the coding.

**Comment by systembolaget** [comment]
Unfortunately, you cannot simulate this on Tinkercad as the FastLED library is needed here. Maybe Adafruit's NeoPixel library, which I don't use for lack of many functions, works with Tinkercad and you can re-write the code with that. Best is to ask for that on Adafruit or Tinkercad forums.
